apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: 192.168.8.100:5000/web:blue
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-blue
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: blue
  type: LoadBalancer
