apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: 192.168.8.100:5000/web:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-green
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: green
  type: LoadBalancer
